version: "3"
services:
  postgres:
    container_name: nestjs-postgres
    image: postgres:latest
    ports:
      - "28432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env.prod
      
  main:
    container_name: main
    restart: always
    build: .
    env_file:
      - .env.prod
    ports:
      - 8888:8888
    command: yarn start:prod
    depends_on:
      - postgres

# networks:
#   postgres:
#     driver: bridge