version: "3"
services:
  postgres:
    container_name: nestjs-postgres
    image: postgres:latest
    ports:
      - "28432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .prod.env
  migrate:
    container_name: main_migrate
    build: .
    restart: on-failure
    env_file:
      - .prod.env
    depends_on:
      - postgres
    command: ["yarn", "migrate" ]
  main:
    container_name: main
    restart: always
    build: .
    # volumes:
    #   - .:/ohif/app/main
    #   - /ohif/app/main/node_modules
    #   - /ohif/app/main/generated
    # command: ["yarn", "start:dev" ]
    env_file:
      - .prod.env
    ports:
      - 8888:8888
    depends_on:
      - migrate