version: "3"
services:
  postgres:
    container_name: nestjs-postgres
    image: postgres:latest
    ports:
      - "28432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env.prod
  migrate:
    container_name: main_migrate
    build: .
    restart: on-failure
    env_file:
      - .env.prod
    depends_on:
      - postgres
    command: ["yarn", "migrate" ]
  main:
    container_name: main
    restart: always
    build: .
    env_file:
      - .env.prod
    ports:
      - 8888:8888
    depends_on:
      - migrate